<h1 style="color:#6C3483" align="center">Numerical Computing with Arrays: NumPy</h1> 

<h2 style="color:#784212" align="center"> Dr. Rajib Debnath </h2> 
<h3 style="color:#784212" align="center">Assistant Professor, CSE, KL University Hyderabad</h3>

# NumPy
Numerical computing with powerful numerical arrays objects, and routines to manipulate them.

In [ ]:
import numpy as np

In [ ]:
np.array?

In [ ]:
np.con*?

In [ ]:
a = np.array([[1,2,3,4,8]])
a1 = np.array([1,2,3,4,8])
a2 = np.array([1,2,3,10,20])

In [ ]:
print(a1.shape, a2.shape)

In [ ]:
print(type(a1), type(a2))

In [ ]:
print(a.ndim)

In [ ]:
print(len(a2))

In [ ]:
a = np.arange(10) # 0 .. n-1  (!)
print(a)

In [ ]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
print(b)

In [ ]:
c = np.linspace(0, 1, 6)   # start, end, num-points
print(c)

In [ ]:
d = np.linspace(0, 1, 5, endpoint=False)
print(d)

In [ ]:
e = np.diag(np.array([1, 2, 3, 4]))
print(e)

In [ ]:
f = np.array([1, 2])
print(f.dtype)

In [ ]:
f = np.array([1.0, 2.0])
print(f.dtype)

In [ ]:
f = np.array([1, 2], dtype=np.int64)
print(f.dtype)

In [ ]:
f = np.array([[1,2],[3,4]], dtype=np.float64)
g = np.array([[5,6],[7,8]], dtype=np.float64)

print(f+g)

In [ ]:
h = np.array([1+2j, 3+4j, 5+6*1j])
print(h)
print(h.dtype)

In [ ]:
i = np.array([True, False, False, True])
print(i)
print(type(i))

In [ ]:
j = np.array(['Bonjour', 'Hello', 'Hallo',])
print(j)
print(j.dtype)

In [ ]:
f = np.zeros((2,2))
print(f)
print(type(f))

In [ ]:
nm = np.matrix('1 2; 3 4')
print(type(nm))
print(nm)

In [ ]:
c = np.ones((3,3))
print(c)

In [ ]:
c = np.full((3,3),10)
print(c)

In [ ]:
c = np.eye((4))
print(c)

In [ ]:
d = np.random.random((2,3))
print(d)

In [ ]:
r = np.random.normal()
print(r)

In [ ]:
r1 = np.random.randint(1,10,100)
print(r1)

In [ ]:
r2 = np.random.randint(1,10,(4,5))
print(r2)

In [ ]:
y = np.empty_like(r2)
print(y)

In [ ]:
y = np.zeros_like(r2)
print(y)

In [ ]:
y = np.ones_like(r2)
print(y)

In [ ]:
print(r2.T) # Transpose
print(nm.T)

In [ ]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
print(np.sqrt(x))

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [ ]:
print(x+y)

print(np.add(x,y))

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print(x)
print(y)
print(v)
print(w)

In [ ]:
print(v.dot(w))
print('---------------')
print(np.dot(v, w))

In [ ]:
print(x.dot(v))
print('---------------')
print(np.dot(x, v))

In [ ]:
print(np.dot(v, x))

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)

In [ ]:
a2d = np.array([[1,2,3],[4,5,6]])
b2d = np.array([[10,4,6],[2,4,6]])
print(a2d.shape)

r, c = b2d.shape
print(r,c)

In [ ]:
c2d = a2d.T # Transpose
print(c2d)
print(a2d)

In [ ]:
# Element wise multiplication
d2d = a2d * b2d
print(d2d)

d2d = np.multiply(a2d, b2d)
print(d2d)

In [ ]:
# Matrix multiplication
e2d = np.dot(a2d,c2d)
print(e2d)

e2d = np.matmul(a2d,c2d)
print(e2d)

In [ ]:
det1 = np.linalg.det(e2d)
print(det1)

In [ ]:
eig, eig1 = np.linalg.eig(e2d)
print(eig)
print(eig1)

In [ ]:
inv1 = np.linalg.inv(e2d)
print(inv1)

In [ ]:
ind = a2d>2
print(ind)

In [ ]:
print(a2d[ind])

In [ ]:
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

In [ ]:
b = a[:2,1:3] #Last exclusive
print(b)

In [ ]:
b[0, 0] = 77 
print(b)
print(a)

In [ ]:
c = np.copy(a)
print(c)

In [ ]:
c[0,0] = 105
print(c)
print(a)

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

print(a[[0, 1, 2], [0, 1, 0]]) ## localtion (0,0), (1,1), (2,0)

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

b = np.array([0, 2, 0, 1])
print(b)

In [ ]:
print(a[np.arange(4), b])

In [ ]:
a[np.arange(4), b] += 10
print(a)

In [ ]:
v = np.array([1,2,3])

In [ ]:
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [ ]:
y = np.zeros_like(x)
print(y)

In [ ]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [ ]:
print(y)
print(x)

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array([1, 0, 1])
print(v)

In [ ]:
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [ ]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([4,5])
print(np.reshape(v, (3, 2)))

In [ ]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print(np.reshape(v, (3, 1)) * w)

In [ ]:
help(np.random)

# References

<p style="font-size:17px">
a) https://www.scipy-lectures.org/intro/numpy/index.html <br>
b) https://docs.scipy.org/doc/numpy/user/quickstart.html <br>
c) https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb <br>
</p>